### ISSUE TITLE
部分代码是不是来自于另一个开源仓库？

### ISSUE THREAD

**Issue by She-yh** [qlwei89/FV2ES#2]
我发现代码和[Multimodal-End2end-Sparse](https://github.com/wenliangdai/Multimodal-End2end-Sparse)这个开源仓库有重合的地方，使用的模型文件也叫mme2e，因为最近在做相关工作，有几个问题想探讨一下

**Comment by MultimodalAffectiveComputing** [comment]
您好，非常感谢您对我们工作的关注！在论文（https://arxiv.org/abs/2209.10170）中已提及，本文工作以开源项目[Multimodal-End2end-Sparse](https://github.com/wenliangdai/Multimodal-End2end-Sparse)为基础，进行了优化，实验结果中也与该基础工作对应的论文方法进行了对比。

如有新的问题，请您或贵团队随时留言，我们将尽快回复。

**Comment by She-yh** [comment]
> 您好，非常感谢您对我们工作的关注！在论文（[https://arxiv.org/abs/2209.10170）中已提及，本文工作以开源项目[Multimodal-End2end-Sparse](https://github.com/wenliangdai/Multimodal-End2end-Sparse)为基础，进行了优化，实验结果中也与该基础工作对应的论文方法进行了对比。](https://arxiv.org/abs/2209.10170%EF%BC%89%E4%B8%AD%E5%B7%B2%E6%8F%90%E5%8F%8A%EF%BC%8C%E6%9C%AC%E6%96%87%E5%B7%A5%E4%BD%9C%E4%BB%A5%E5%BC%80%E6%BA%90%E9%A1%B9%E7%9B%AE%5BMultimodal-End2end-Sparse%5D(https://github.com/wenliangdai/Multimodal-End2end-Sparse)%E4%B8%BA%E5%9F%BA%E7%A1%80%EF%BC%8C%E8%BF%9B%E8%A1%8C%E4%BA%86%E4%BC%98%E5%8C%96%EF%BC%8C%E5%AE%9E%E9%AA%8C%E7%BB%93%E6%9E%9C%E4%B8%AD%E4%B9%9F%E4%B8%8E%E8%AF%A5%E5%9F%BA%E7%A1%80%E5%B7%A5%E4%BD%9C%E5%AF%B9%E5%BA%94%E7%9A%84%E8%AE%BA%E6%96%87%E6%96%B9%E6%B3%95%E8%BF%9B%E8%A1%8C%E4%BA%86%E5%AF%B9%E6%AF%94%E3%80%82)
> 
> 如有新的问题，请您或贵团队随时留言，我们将尽快回复。

@MultimodalAffectiveComputing 
亲爱的作者，

感谢您的回复，我也看见了您在另一个issue下的回复，我将继续跟进。
感谢您对自己代码的分享
为我给您造成的麻烦表示抱歉，我将关闭这个issue

祝工作顺利！
