### ISSUE TITLE
CUDA out of memory on the CMU-MOSEI dataset

### ISSUE THREAD

**Issue by sklee2014** [qlwei89/FV2ES#3]
I'm running experiments on RTX 3090 32GB GPU and there is no problem with the IEMOCAP dataset.

However, with the CMU-MOSEI dataset, there  is a CUDA out of memory error even though I set the batch size as 2.
(python main.py -lr=4.5e-6 -ep=30 -mod=tav -bs=2 --img-interval=500 --early-stop=6 --loss=bce --cuda=0 --model=mme2e --num-emotions=6 --trans-dim=64 --trans-nlayers=4 --trans-nheads=4 --text-lr-factor=10 --text-model-size=base --text-max-len=100)

Have you used multi-gpu for the experiments or are there some parameters to tune for the CMU-MOSEI experiments?

**Comment by MultimodalAffectiveComputing** [comment]
Hi Sun, we used one Tesla V100 (4 core, 32G) GPU on Jiutian platform (https://jiutian.10086.cn) for training. The platform is from China Mobile Company and it is free. In addition to the parameters you mentioned, we also set -dataset=mosei. By the way, we have uploaded our pertained models on both of these two datasets, please check the readme file. You can also use them directly to do the fine-tune work.

**Comment by MultimodalAffectiveComputing** [comment]
You can find that the accs of uploaded pretrained models are higher than those in our paper. That is because we just chose the average performance from 30 epochs in our paper, and we saved the pertained models with the highest  performance using early stop=6 for future fine-tuning.

If you have other questions, do not hesitate to contact us. Thanks!

**Comment by sklee2014** [comment]
Oh, thank you for the reply! I think I'll have to look more into the codes. By the way, the batch size should be 8, right?

**Comment by MultimodalAffectiveComputing** [comment]
Hi sklee, the batch size is not fixed, you can try various values according to your GPU resources. Thanks again for your interests on our project.
